import prisma from "../config/database.config";

// Domain -> subjects, aligned with what's actually examined in the
// Cameroonian GCE O/A-Level and university-prep curriculum.
// Aligned with the official Cameroon GCE Board O-Level/A-Level subject
// lists and the Baccalauréat séries (A/C/D/TI/G) subjects, so tutors and
// search filters map onto what students actually sit exams in.
export const defaultSubjectsByDomain: Record<string, string[]> = {
  "Agriculture & Environment": [
    "Mining and Petroleum",
    "Mining and Petroleum Production",
    "Mining and Petroleum Production (GCE A Level)",
    "Petroleum Process",
    "Petroleum Process (GCE A Level)",
    "Petroleum and Bio Products Production",
    "Petroleum and Bio Products Production (GCE A Level)",
    "Quality Hygiene, Safety and Environment",
    "Quality Hygiene, Safety and Environment (TVE Intermediate Level)",
  ],
  "Business, Accounting & Economics": [
    "Accounting",
    "Accounting (GCE A Level)",
    "Accounting (GCE O Level)",
    "Architectural Project Management",
    "Architectural Project Management (GCE A Level)",
    "Building Construction Project Management",
    "Building Construction Project Management (GCE A Level)",
    "Business Management",
    "Business Management (GCE A Level)",
    "Business Mathematics",
    "Business Mathematics (GCE A Level)",
    "Business Mathematics (TVE Intermediate Level)",
    "Business, Accounting & Economics",
    "Catering Management & Dietetics",
    "Catering Management & Dietetics (GCE A Level)",
    "Commerce",
    "Commerce (GCE O Level)",
    "Commerce (TVE Intermediate Level)",
    "Commerce and Finance",
    "Commerce and Finance (GCE A Level)",
    "Corporate Accounting",
    "Corporate Accounting (GCE A Level)",
    "Cost and Management Accounting",
    "Cost and Management Accounting (GCE A Level)",
    "Digital Marketing Practice",
    "Digital Marketing Practice (GCE A Level)",
    "Digital Marketing Practice (TVE Intermediate Level)",
    "Economics",
    "Economics (GCE A Level)",
    "Economics (GCE O Level)",
    "Economics (TVE Intermediate Level)",
    "Financial Accounting/Computer Aided Accounting",
    "Financial Accounting/Computer Aided Accounting (GCE A Level)",
    "Forestry Management and Techniques",
    "Home Economics",
    "Information Management Systems for Business",
    "Information Management Systems for Business (GCE A Level)",
    "International Financial Accounting/Computer Aided Accounting",
    "International Financial Accounting/Computer Aided Accounting (TVE Intermediate Level)",
    "Marketing",
    "Marketing Skills",
    "Marketing Skills (GCE A Level)",
    "Office Practice",
    "Office Practice (TVE Intermediate Level)",
    "Ohada Financial Accounting",
    "Ohada Financial Accounting (TVE Intermediate Level)",
    "Ohada Financial Reporting",
    "Ohada Financial Reporting (TVE Intermediate Level)",
    "Plumbing Project Management",
    "Plumbing Project Management (GCE A Level)",
    "Principles and Practice of Taxation",
    "Principles and Practice of Taxation (GCE A Level)",
    "Production Management",
    "Production Management (GCE A Level)",
    "Professional Marketing Practice",
    "Professional Marketing Practice (GCE A Level)",
    "Public Works Project Management",
    "Public Works Project Management (GCE A Level)",
    "Resource Management on Home Studies",
    "Resource Management on Home Studies (TVE Intermediate Level)",
    "Resource Management on Home Studies and Social Life",
    "Resource Management on Home Studies and Social Life (GCE A Level)",
    "Secretarial Administration and Communication",
    "Sustainable Management of Forest Resources",
    "Sustainable Management of Forest Resources (GCE A Level)",
    "Taxation",
    "Taxation and Information Management Systems",
  ],
  "Health, Food & Biomedical": [
    "Family Life Education and Gerontology",
    "Family Life Education and Gerontology (GCE A Level)",
    "Family Life Education and Gerontology (TVE Intermediate Level)",
    "Food Nutrition and Health",
    "Food Nutrition and Health (TVE Intermediate Level)",
    "Food Processing and Preservation",
    "Food Processing and Preservation (GCE A Level)",
    "Food and Nutrition",
    "Food and Nutrition (GCE O Level)",
    "Hospital and Biomedical Maintenance",
    "Medical Devices",
    "Medical Devices (GCE A Level)",
  ],
  "Humanities & Social Sciences": [
    "Citizenship Education",
    "Citizenship Education (GCE O Level)",
    "Citizenship Education (TVE Intermediate Level)",
    "Economic Geography",
    "Economic Geography (TVE Intermediate Level)",
    "Geography",
    "Geography (GCE A Level)",
    "Geography (GCE O Level)",
    "History",
    "History (GCE A Level)",
    "History (GCE O Level)",
    "Land Survey Law",
    "Land Survey Law (GCE A Level)",
    "Law",
    "Law (GCE A Level)",
    "Law and Government",
    "Law and Government (TVE Intermediate Level)",
    "Logic",
    "Logic (GCE O Level)",
    "Philosophy",
    "Philosophy (GCE A Level)",
    "Religious Studies",
    "Religious Studies (GCE A Level)",
    "Religious Studies (GCE O Level)",
    "Religious Studies (TVE Intermediate Level)",
  ],
  "Languages & Literature": [
    "Aesthetics of the French Novel",
    "African and Commonwealth Literature",
    "African and Francophone Literature",
    "Contrastive Linguistics",
    "English Grammar and Lexicology",
    "English Language",
    "English Language (GCE A Level)",
    "English Language (GCE O Level)",
    "English Language (TVE Intermediate Level)",
    "English-French Translation",
    "French",
    "French (GCE A Level)",
    "French (GCE O Level)",
    "French (TVE Intermediate Level)",
    "Introduction to Comparative Studies in English and French",
    "Introduction to Contrastive French Studies",
    "Introduction to French Oral Expression",
    "Introduction to French Written Expression",
    "Introduction to Linguistics",
    "Introduction to Spoken English",
    "Introduction to Translation",
    "Introduction to Written English",
    "Languages & Literature",
    "Linguistics",
    "Literature in English",
    "Literature in English (GCE A Level)",
    "Literature in English (GCE O Level)",
    "Normative Grammar",
    "Professional English (Language and Organisational Communication)",
    "Professional English (Language and Organisational Communication) (GCE A Level)",
    "Special Bilingual Education French",
    "Special Bilingual Education French (GCE A Level)",
    "Special Bilingual Education French (GCE O Level)",
    "The English Novel",
    "Translation",
  ],
  "Mathematics & Statistics": [
    "Additional Mathematics",
    "Additional Mathematics (GCE O Level)",
    "Applied and Fluid Mechanics",
    "Applied and Fluid Mechanics (GCE A Level)",
    "Architectural Applied Mechanics",
    "Architectural Applied Mechanics (GCE A Level)",
    "Automobile Mechanics",
    "Automobile Repair Mechanics",
    "Building Construction Applied Mechanics",
    "Building Construction Applied Mechanics (GCE A Level)",
    "Building Construction Surveying and Soil Mechanics",
    "Building Construction Surveying and Soil Mechanics (GCE A Level)",
    "Drawing and Architectural Modelling",
    "Drawing and Architectural Modelling (GCE A Level)",
    "Further Mathematics",
    "Further Mathematics (GCE A Level)",
    "Manufacturing Mechanics",
    "Mathematics",
    "Mathematics (GCE A Level)",
    "Mathematics (TVE Intermediate Level)",
    "Mechanics",
    "Public Works Applied Mechanics",
    "Public Works Applied Mechanics (GCE A Level)",
    "Pure Mathematics",
    "Pure Mathematics With Mechanics",
    "Pure Mathematics With Mechanics (GCE A Level)",
    "Pure Mathematics With Statistics",
    "Pure Mathematics With Statistics (GCE A Level)",
    "Statistics",
    "Surveying, Soil Mechanics and Materials",
    "Surveying, Soil Mechanics and Materials (TVE Intermediate Level)",
    "Wood Cabinet Applied Mechanics",
    "Wood Cabinet Applied Mechanics (GCE A Level)",
    "mathematics (GCE O Level)",
  ],
  "Other / Unclassified": [
    ") of the ERASMUS+ Programme (2026-2027)",
    "Architectural Technology and Practice",
    "Architectural Technology and Practice (GCE A Level)",
    "Automatic Control of Electrical Machines",
    "Automatic Control of Electrical Machines (GCE A Level)",
    "Automation",
    "Automation (GCE A Level)",
    "Banking",
    "Circuit Analysis",
    "Circuit Analysis (GCE A Level)",
    "Cybersecurity",
    "Design of Electrical Installations",
    "Design of Electrical Installations (GCE A Level)",
    "Diesel Engine Technology",
    "Diesel Engine Technology (GCE A Level)",
    "Electrical Machines",
    "Electrical Machines (GCE A Level)",
    "Electrical Machines (TVE Intermediate Level)",
    "Electrical Technology and Diagram",
    "Electrical Technology and Diagram (TVE Intermediate Level)",
    "Engineering Drawing",
    "Engineering Drawing (TVE Intermediate Level)",
    "Entrepreneurship",
    "Entrepreneurship (GCE A Level)",
    "Entrepreneurship (TVE Intermediate Level)",
    "Fashion and Fabric Design",
    "Fashion and Fabric Design (GCE A Level)",
    "Fashion and Fabric Design (TVE Intermediate Level)",
    "Finishing and Restoration Techniques",
    "Finishing and Restoration Techniques (GCE A Level)",
    "Forest Geomatics",
    "Forest Geomatics (GCE A Level)",
    "Forest Operations",
    "Forest Operations (GCE A Level)",
    "Forest Sciences",
    "Forest Sciences (GCE A Level)",
    "Furniture Design and Drawing",
    "Furniture Design and Drawing (GCE A Level)",
    "Information Processing",
    "Information Processing (GCE A Level)",
    "Information Processing (TVE Intermediate Level)",
    "Log Processing",
    "Log Processing (GCE A Level)",
    "Marking out (Development)",
    "Marking out (Development) (GCE A Level)",
    "Material Technology and Workshop Processes",
    "Material Technology and Workshop Processes (TVE Intermediate Level)",
    "Material and Paint Technology",
    "Material and Paint Technology (TVE Intermediate Level)",
    "Mechanical Design",
    "Mechanical Design (GCE A Level)",
    "Mechanical Drawing",
    "Mechanical Drawing (TVE Intermediate Level)",
    "Mechanical Technology",
    "Mechanical Technology (TVE Intermediate Level)",
    "Mechanical Technology and Fluid Power",
    "Mechanical Technology and Fluid Power (GCE A Level)",
    "Networks",
    "Organisation of Administrative Works and Technology (Filing and Office Equipment)",
    "Organisation of Administrative Works and Technology (Filing and Office Equipment) (GCE A Level)",
    "Petrochemistry and Bioproducts",
    "Processing Engineering",
    "Processing Engineering (GCE A Level)",
    "Product Mastery",
    "Product Mastery (TVE Intermediate Level)",
    "Production Processes",
    "Production Processes (GCE A Level)",
    "Professional Communication Skills",
    "Professional Communication Skills (GCE A Level)",
    "Professional Communication Techniques",
    "Professional Communication Techniques (TVE Intermediate Level)",
    "Refrigeration Installation",
    "Refrigeration Installation (GCE A Level)",
    "Refrigeration Repairs",
    "Refrigeration Repairs (TVE Intermediate Level)",
    "Sales Methods and Communication",
    "Sales Methods and Communication (TVE Intermediate Level)",
    "Technical & Vocational",
    "Textile Technology and Equipment",
    "Textile Technology and Equipment (GCE A Level)",
    "Textile Technology and Equipment (TVE Intermediate Level)",
    "Topographical Drawing",
    "Topographical Drawing (GCE A Level)",
    "Vehicle Technology",
    "Vehicle Technology (TVE Intermediate Level)",
    "Water Supply and Drainage Networks Processes",
    "Water Supply and Drainage Networks Processes (GCE A Level)",
    "Work Organization",
    "Work Organization (GCE A Level)",
    "Workshop Processes and Material",
    "Workshop Processes and Material (TVE Intermediate Level)",
    "Workshop Processes and Materials",
    "Workshop Processes and Materials (GCE A Level)",
  ],
  Science: [
    "Air Conditioning Electricity",
    "Air Conditioning Electricity (GCE A Level)",
    "Analytical Chemistry",
    "Analytical and Physical Chemistry",
    "Analytical and Physical Chemistry (GCE A Level)",
    "Applied Biochemistry /Microbiology",
    "Applied Biochemistry /Microbiology (GCE A Level)",
    "Biology",
    "Biology (GCE A Level)",
    "Biology (GCE O Level)",
    "Botany",
    "Chemistry",
    "Chemistry (GCE A Level)",
    "Chemistry (GCE O Level)",
    "Cosmetics and Pharmacology",
    "Cosmetics and Pharmacology Process",
    "Cosmetics and Pharmacology Process (GCE A Level)",
    "Ecology",
    "Electricity",
    "Electricity of Refrigeration",
    "Electricity of Refrigeration (TVE Intermediate Level)",
    "Engineering Science",
    "Engineering Science (GCE A Level)",
    "Engineering Science (TVE Intermediate Level)",
    "Environmental Science",
    "Food Science and Nutrition",
    "Food Science and Nutrition (GCE A Level)",
    "General Chemistry",
    "Genetics",
    "Geology",
    "Geology (GCE A Level)",
    "Geology (GCE O Level)",
    "Human Biology",
    "Human Biology (GCE O Level)",
    "Inorganic Chemistry",
    "Magnetism",
    "Material Science and Processes",
    "Material Science and Processes (GCE A Level)",
    "Material Science and Processes (TVE Intermediate Level)",
    "Microbiology",
    "Modern Physics",
    "Natural Science",
    "Natural Science (GCE A Level)",
    "Natural Science (TVE Intermediate Level)",
    "Optics",
    "Organic Chemistry",
    "Organic and Applied Biochemistry",
    "Organic and Applied Biochemistry (GCE A Level)",
    "Physical Chemistry",
    "Physics",
    "Physics (GCE A Level)",
    "Physics (GCE O Level)",
    "Physiology",
    "Science",
    "Thermodynamics",
    "Zoology",
  ],
  "Series / Track": [
    "Series A",
    "Series ABI",
    "Series C",
    "Series D",
    "Series E",
    "Series SH",
    "Series TI",
  ],
  "Specialty / Series": [
    "ACA",
    "AF1",
    "AF2",
    "AF3",
    "AMEB",
    "BANQUE",
    "BIJO",
    "CG",
    "CHME",
    "CHTI",
    "CMA/MVPL",
    "CMA/MVT",
    "COMPTABILITE",
    "COMPTABLES",
    "COUT",
    "ELAD",
    "ELAU",
    "ELIE",
    "ELNI",
    "ELPR",
    "ESF",
    "F1",
    "F2",
    "F3",
    "F4-BA",
    "F4-BE",
    "F4-TP",
    "F5",
    "F6-BIOLO",
    "F6-BIPE",
    "F6-Biotech",
    "F6-COPH",
    "F6-MIPE",
    "F8",
    "FIG",
    "FRCL",
    "G.T",
    "HO-CU",
    "HO-HE",
    "HO-RB",
    "IB-TMG",
    "INSA",
    "IS/RH",
    "MACO",
    "MAGE",
    "MEM",
    "MENU",
    "MHB",
    "MISE",
    "SECRETAIRE",
    "SECRETARIAT",
    "SES",
    "TAG/AQ",
    "TAG/MEA",
    "TAG/PCLC",
    "TAG/PCP",
    "TAG/PM",
    "TAG/PMF",
    "TAG/PP",
    "TAG/PPS",
    "TAG/PRT",
    "TAG/TCPA",
    "TGF",
    "TO-AAT",
    "TO-AV",
  ],
  "Technical & Vocational": [
    "Air Conditioning Repairs",
    "Air Conditioning Repairs (GCE A Level)",
    "Air Conditioning and Ventilation",
    "Automobile Bodywork Painting",
    "Automobile Construction-Heavy Duty Vehicle Maintenance",
    "Automobile Construction-Light Vehicle Maintenance",
    "Bespoke Tailoring",
    "Building Construction Drawing",
    "Building Construction Drawing (GCE A Level)",
    "Building Construction Drawing (TVE Intermediate Level)",
    "Building Construction Technology and Practice",
    "Building Construction Technology and Practice (GCE A Level)",
    "Carpentry",
    "Carpentry (TVE Intermediate Level)",
    "Carpentry /Joinery Drawing",
    "Carpentry /Joinery Drawing (TVE Intermediate Level)",
    "Carpentry and Joinery",
    "Civil Engineering",
    "Civil Engineering - Architectural Draftsmanship",
    "Civil Engineering - Building Construction",
    "Civil Engineering - Public Works",
    "Clothing Industry",
    "Construction Processes",
    "Construction Processes (GCE A Level)",
    "Construction Processes and Building Practice",
    "Construction Processes and Building Practice (TVE Intermediate Level)",
    "Electrical Power System",
    "Fundamental Refrigeration and Air Conditioning",
    "Fundamental Refrigeration and Air Conditioning (TVE Intermediate Level)",
    "Heating Ventilation and Air Conditioning",
    "Heating, Ventilation and Air Conditioning (GCE A Level)",
    "Industrial Automation",
    "Industrial Automation (GCE A Level)",
    "Industrial Automation and Numerical Control Machining",
    "Industrial Automation and Numerical Control Machining (GCE A Level)",
    "Joinery",
    "Joinery (TVE Intermediate Level)",
    "Maintenance and Machine Control",
    "Maintenance and Machine Control (GCE A Level)",
    "Maintenance of Electro-Mechanical Equipment",
    "Manufacturing Processes",
    "Manufacturing Processes (TVE Intermediate Level)",
    "Mechanical Construction and Development",
    "Mechanical Construction and Development (TVE Intermediate Level)",
    "Metal Construction Drawing",
    "Metal Construction Drawing (TVE Intermediate Level)",
    "Metal Works and Industrial Piping",
    "Metal and Industrial Pipe Work",
    "Metal and Industrial Pipe Work (GCE A Level)",
    "Pattern Making and Garment Construction",
    "Pattern Making and Garment Construction (GCE A Level)",
    "Pattern Making and Garment Construction (TVE Intermediate Level)",
    "Plumbing",
    "Plumbing Drawing",
    "Plumbing Drawing (GCE A Level)",
    "Plumbing Maintenance",
    "Plumbing Maintenance (TVE Intermediate Level)",
    "Plumbing Technology",
    "Plumbing Technology (TVE Intermediate Level)",
    "Public Works Construction Drawing",
    "Public Works Construction Drawing (GCE A Level)",
    "Public Works Technology and Practice",
    "Public Works Technology and Practice (GCE A Level)",
    "Special Techniques in Surveying",
    "Special Techniques in Surveying (GCE A Level)",
    "Surveying SURV",
    "Welding Fabrication",
    "Welding Fabrication Work",
    "Welding Fabrication Work (TVE Intermediate Level)",
    "Wood Cabinet-Making",
    "Wood Preservation and Seasoning",
    "Wood Preservation and Seasoning (GCE A Level)",
    "Wood Processing",
    "Wood Processing Regulations",
    "Wood Processing Regulations (GCE A Level)",
    "Wood Study and Wood Grading",
    "Wood Study and Wood Grading (GCE A Level)",
  ],
  "Technology & ICT": [
    "Alarm Systems",
    "Alarm Systems (GCE A Level)",
    "Audio Visual Systems",
    "Audio Visual Systems (GCE A Level)",
    "Chassis Systems and Transmission",
    "Chassis Systems and Transmission (GCE A Level)",
    "Communication Systems",
    "Communication Systems (GCE A Level)",
    "Computer Science",
    "Computer Science (GCE A Level)",
    "Computer Science (GCE O Level)",
    "Computer Science (TVE Intermediate Level)",
    "Database Administration",
    "Design of Electronic Systems",
    "Design of Electronic Systems (GCE A Level)",
    "Digital Processing and Survey Technology",
    "Digital Processing and Survey Technology (GCE A Level)",
    "Electrical Power Systems",
    "Electrical and Electronic Circuit",
    "Electrical and Electronic Circuit (TVE Intermediate Level)",
    "Electrical and Electronic Systems",
    "Electrical and Electronic Systems (GCE A Level)",
    "Electrical and Electronic Technology",
    "Electrical and Electronic Technology (TVE Intermediate Level)",
    "Electrical, Electronics and Refrigeration Systems",
    "Electrical, Electronics and Refrigeration Systems (GCE A Level)",
    "Electrical/Electronics Applied Mechanics",
    "Electrical/Electronics Applied Mechanics (GCE A Level)",
    "Electronic Circuits",
    "Electronic Circuits (TVE Intermediate Level)",
    "Electronic Diagrams",
    "Electronic Diagrams (GCE A Level)",
    "Electronic Systems",
    "Electronic Systems (TVE Intermediate Level)",
    "Electronics",
    "Engine Systems",
    "Engine Systems (GCE A Level)",
    "Fundamental and Power Electronics",
    "Fundamental and Power Electronics (GCE A Level)",
    "Hydraulics and Chassis Systems",
    "Hydraulics and Chassis Systems (GCE A Level)",
    "Information and Communication Technology",
    "Information and Communication Technology (GCE A Level)",
    "Information and Communication Technology (TVE Intermediate Level)",
    "Installation and Maintenance of Electronic Systems",
    "Maintenance of Automated Production Systems",
    "Maintenance of Automated Production Systems (GCE A Level)",
    "Maintenance of Electrical ,Electronic and Refrigeration Systems",
    "Maintenance of Electrical ,Electronic and Refrigeration Systems (GCE A Level)",
    "Maintenance of Mechanical, Pneumatic and Hydraulic Systems",
    "Maintenance of Mechanical, Pneumatic and Hydraulic Systems (GCE A Level)",
    "Microprocessor and Computer Technology",
    "Microprocessor and Computer Technology (GCE A Level)",
    "Network and Telecommunication Systems",
    "Network and Telecommunication Systems (GCE A Level)",
    "Photovoltaic Systems",
    "Photovoltaic Systems (TVE Intermediate Level)",
    "Plumbing Network Drawing",
    "Plumbing Network Drawing (TVE Intermediate Level)",
    "Plumbing and Hydraulic Installation Systems",
    "Plumbing and Installation Systems",
    "Power Electronics",
    "Power Electronics (GCE A Level)",
    "Software Engineering",
    "Technology & ICT",
  ],
};

const seedSubjectDomains = async () => {
  console.log("🌱 Seeding subject domains...");

  let created = 0;
  let skipped = 0;

  await prisma.$transaction(async (tx) => {
    for (const domainName of Object.keys(defaultSubjectsByDomain)) {
      const exists = await tx.subjectDomain.findUnique({
        where: { name: domainName },
      });
      if (exists) {
        skipped++;
        continue;
      }
      await tx.subjectDomain.create({ data: { name: domainName } });
      created++;
    }
  });

  console.log(
    `✅ Subject domains seeded: ${created} created, ${skipped} skipped`
  );
};

const seedSubjects = async () => {
  console.log("🌱 Seeding subjects...");

  let created = 0;
  let skipped = 0;
  let domainsMissing = 0;

  for (const [domainName, subjectNames] of Object.entries(
    defaultSubjectsByDomain
  )) {
    const domain = await prisma.subjectDomain.findUnique({
      where: { name: domainName },
    });
    if (!domain) {
      domainsMissing++;
      continue;
    }

    await prisma.$transaction(async (tx) => {
      for (const subjectName of subjectNames) {
        const exists = await tx.subject.findFirst({
          where: { name: subjectName, domainId: domain.id },
        });
        if (exists) {
          skipped++;
          continue;
        }
        await tx.subject.create({
          data: { name: subjectName, domainId: domain.id },
        });
        created++;
      }
    });
  }

  console.log(
    `✅ Subjects seeded: ${created} created, ${skipped} skipped` +
      (domainsMissing > 0 ? `, ${domainsMissing} domain(s) not found` : "")
  );
};

export { seedSubjectDomains, seedSubjects };
